package material

// BUG(toqueteos): Remove "Item*" prefix from all non-necessary materials. Add
// it as suffix to required ones.
const (
	ItemIronShovel         Material = iota + 256 // 256
	ItemIronPickaxe                              // 257
	ItemIronAxe                                  // 258
	ItemFlintAndSteel                            // 259
	ItemApple                                    // 260
	ItemBow                                      // 261
	ItemArrow                                    // 262
	ItemCoal                                     // 263 // D
	ItemDiamond                                  // 264
	ItemIronIngot                                // 265
	ItemGoldIngot                                // 266
	ItemIronSword                                // 267
	ItemWoodSword                                // 268
	ItemWoodShovel                               // 269
	ItemWoodPickaxe                              // 270
	ItemWoodAxe                                  // 271
	ItemStoneSword                               // 272
	ItemStoneShovel                              // 273
	ItemStonePickaxe                             // 274
	ItemStoneAxe                                 // 275
	ItemDiamondSword                             // 276
	ItemDiamondShovel                            // 277
	ItemDiamondPickaxe                           // 278
	ItemDiamondAxe                               // 279
	ItemStick                                    // 280
	ItemBowl                                     // 281
	ItemMushroomStew                             // 282
	ItemGoldenSword                              // 283
	ItemGoldenShovel                             // 284
	ItemGoldenPickaxe                            // 285
	ItemGoldenAxe                                // 286
	ItemString                                   // 287
	ItemFeather                                  // 288
	ItemGunpowder                                // 289
	ItemWoodHoe                                  // 290
	ItemStoneHoe                                 // 291
	ItemIronHoe                                  // 292
	ItemDiamondHoe                               // 293
	ItemGoldHoe                                  // 294
	ItemSeeds                                    // 295
	ItemWheat                                    // 296
	ItemBread                                    // 297
	ItemLeatherHelmet                            // 298
	ItemLeatherChestplate                        // 299
	ItemLeatherLeggings                          // 300
	ItemLeatherBoots                             // 301
	ItemChainHelmet                              // 302
	ItemChainChestplate                          // 303
	ItemChainLeggings                            // 304
	ItemChainBoots                               // 305
	ItemIronHelmet                               // 306
	ItemIronChestplate                           // 307
	ItemIronLeggings                             // 308
	ItemIronBoots                                // 309
	ItemDiamondHelmet                            // 310
	ItemDiamondChestplate                        // 311
	ItemDiamondLeggings                          // 312
	ItemDiamondBoots                             // 313
	ItemGoldHelmet                               // 314
	ItemGoldChestplate                           // 315
	ItemGoldLeggings                             // 316
	ItemGoldBoots                                // 317
	ItemFlint                                    // 318
	ItemRawPorkchop                              // 319
	ItemCookedPorkchop                           // 320
	ItemPainting                                 // 321
	ItemAppleGolden                              // 322 // D
	ItemSign                                     // 323
	ItemDoorWood                                 // 324
	ItemBucket                                   // 325
	ItemBucketWater                              // 326
	ItemBucketLava                               // 327
	ItemMinecart                                 // 328
	ItemSaddle                                   // 329
	ItemDoorIron                                 // 330
	ItemRedstone                                 // 331
	ItemSnowball                                 // 332
	ItemBoat                                     // 333
	ItemLeather                                  // 334
	ItemMilk                                     // 335
	ItemBrick                                    // 336
	ItemClay                                     // 337
	ItemSugarCanes                               // 338
	ItemPaper                                    // 339
	ItemBook                                     // 340
	ItemSlimeball                                // 341
	ItemMinecartChest                            // 342
	ItemMinecartFurnace                          // 343
	ItemEgg                                      // 344
	ItemCompass                                  // 345
	ItemFishingRod                               // 346
	ItemClock                                    // 347
	ItemGlowstoneDust                            // 348
	ItemRawFish                                  // 349
	ItemCookedFish                               // 350
	ItemDye                                      // 351 // D
	ItemBone                                     // 352
	ItemSugar                                    // 353
	ItemCake                                     // 354
	ItemBed                                      // 355
	ItemRedstoneRepeater                         // 356
	ItemCookie                                   // 357
	ItemMap                                      // 358
	ItemShears                                   // 359
	ItemMelon                                    // 360
	ItemSeedsPumpkin                             // 361
	ItemSeedsMelon                               // 362
	ItemRawSteak                                 // 363
	ItemCookedSteak                              // 364
	ItemRawChicken                               // 365
	ItemCookedChicken                            // 366
	ItemRottenFlesh                              // 367
	ItemEnderPearl                               // 368
	ItemBlazeRod                                 // 369
	ItemGhastTear                                // 370
	ItemGoldNugget                               // 371
	ItemNetherWart                               // 372
	ItemPotion                                   // 373 // D
	ItemGlassBottle                              // 374
	ItemEyeSpider                                // 375
	ItemEyeSpiderFermented                       // 376
	ItemBlazePowder                              // 377
	ItemMagmaCream                               // 378
	ItemBrewingStand                             // 379
	ItemCauldron                                 // 380
	ItemEnderEye                                 // 381
	ItemGlisteringMelon                          // 382
	ItemSpawnEgg                                 // 383 // D
	ItemBottleOfEnchanting                       // 384
	ItemFireCharge                               // 385
	ItemBookAndQuill                             // 386
	ItemBookWritten                              // 387
	ItemEmerald                                  // 388
	ItemItemFrame                                // 389
	ItemFlowerPot                                // 390
	ItemCarrot                                   // 391
	ItemPotato                                   // 392
	ItemPotatoBaked                              // 393
	ItemPotatoPoisonous                          // 394
	ItemMapEmpty                                 // 395
	ItemCarrotGolden                             // 396
	ItemSkull                                    // 397 // D
	ItemCarrotStick                              // 398
	ItemNetherStar                               // 399
	ItemPumpkinPie                               // 400
	ItemFireworkRocket                           // 401
	ItemFireworkStar                             // 402
	ItemBookEnchanted                            // 403
	ItemRedstoneComparator                       // 404
	ItemNetherBrick                              // 405
	ItemQuartz                                   // 406
	ItemMinecartTnt                              // 407
	ItemMinecartHopper                           // 408
)
